openapi: "3.0.0"
info:
  title: Advertiser API
  version: 1.0.0
  description: Advertiser management and retrieval
tags:
  - name: Advertiser
    description: Advertiser management and retrieval
paths:
  /api/advertiser/createAdvertiser:
    post:
      tags:
        - Advertiser
      summary: Create a new advertiser
      description: Create a new advertiser in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                phone_number:
                  type: string
                activities:
                  type: array
                  items:
                    type: string
                documents_required:
                  type: array
                  items:
                    type: string
                link_to_website:
                  type: string
                hotline:
                  type: string
                about:
                  type: string
                logo:
                  type: string
                company_profile:
                  type: string
      responses:
        200:
          description: Advertiser created.
        400:
          description: Bad request.
        500:
          description: Internal server error.
  /api/advertiser/getAdvertiserByEmail/{email}:
    get:
      tags:
        - Advertiser
      summary: Get advertiser by email
      parameters:
        - in: path
          name: email
          schema:
            type: string
          required: true
          description: Email of advertiser
      responses:
        200:
          description: Advertiser found
        400:
          description: Bad request
        500:
          description: Internal server error
  /api/advertiser/updateAdvertiser/{email}:
    put:
      tags:
        - Advertiser
      summary: Update advertiser by email
      parameters:
        - in: path
          name: email
          schema:
            type: string
          required: true
          description: Email of advertiser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                phone_number:
                  type: string
                activities:
                  type: array
                  items:
                    type: string
                documents_required:
                  type: array
                  items:
                    type: string
                link_to_website:
                  type: string
                hotline:
                  type: string
                about:
                  type: string
                logo:
                  type: string
                company_profile:
                  type: string
      responses:
        200:
          description: Advertiser updated
        400:
          description: Bad request
        500:
          description: Internal server error
  /api/advertiser/deleteAdvertiser/{email}:
    delete:
      tags:
        - Advertiser
      summary: Delete advertiser by email
      parameters:
        - in: path
          name: email
          schema:
            type: string
          required: true
          description: Email of advertiser
      responses:
        200:
          description: Advertiser deleted
        400:
          description: Bad request
        500:
          description: Internal server error
  /api/advertiser/deleteAdvertiserAccountRequest/{email}:
    delete:
      tags:
        - Advertiser
      summary: Request deletion for advertiser
      description: 
        Deletes the account and hides all their activities ONLY if no current upcoming activity has been booked by tourists.
        Activities are shown only to the admin and in history of tourists.
      parameters:
        - in: path
          name: email
          required: true
          description: The advertiser email that they registered with
          schema:
            type: string
      responses:
        200:
          description: Account successfully deleted
        404:
          description: The email was unable to find an advertiser with that email, or the person having that email is not an advertiser.
        400:
          description: The advertiser still has upcoming activity(ies) that are booked by tourists.
