openapi: "3.0.0"
info:
  title: Amadeus API
  version: 1.0.0
  description: Amadeus External API management
tags:
  - name: Amadeus
    description: Amadeus External API management
components:
  schemas:
    FlightOffersOutput:
      type: object
      properties:
        data:
          type: object
          properties:
            flightOffers:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  source:
                    type: string
                  instantTicketingRequired:
                    type: boolean
                  nonHomogeneous:
                    type: boolean
                  oneWay:
                    type: boolean
                  lastTicketingDate:
                    type: string
                  numberOfBookableSeats:
                    type: number
                  itineraries:
                    type: array
                    items:
                      type: object
                      properties:
                        duration:
                          type: string
                        segments:
                          type: array
                          items:
                            type: object
                            properties:
                              departure:
                                type: object
                                properties:
                                  iataCode:
                                    type: string
                                  at:
                                    type: string
                              arrival:
                                type: object
                                properties:
                                  iataCode:
                                    type: string
                                  at:
                                    type: string
                              carrierCode:
                                type: string
                              number:
                                type: string
                              aircraft:
                                type: object
                                properties:
                                  code:
                                    type: string
                              operating:
                                type: object
                                properties:
                                  carrierCode:
                                    type: string
                                  number:
                                    type: string
                              duration:
                                type: string
                              id:
                                type: string
                  price:
                    type: object
                    properties:
                      currency:
                        type: string
                      total:
                        type: string
                      base:
                        type: string
                      fees:
                        type: array
                        items:
                          type: object
                          properties:
                            amount:
                              type: string
                            type:
                              type: string
                      grandTotal:
                        type: string
                  pricingOptions:
                    type: object
                    properties:
                      fareType:
                        type: array
                        items:
                          type: string
                      includedCheckedBagsOnly:
                        type: boolean
                  validatingAirlineCodes:
                    type: array
                    items:
                      type: string
                  travelerPricings:
                    type: array
                    items:
                      type: object
                      properties:
                        travelerId:
                          type: string
                        fareOption:
                          type: string
                        travelerType:
                          type: string
                        price:
                          type: object
                          properties:
                            currency:
                              type: string
    HotelOffersOutput:
      type: object
      properties:
        data:
          type: object
          properties:
            hotelOffers:
              type: array
              items:
                type: object
                properties:
                  hotelId:
                    type: string
                  roomType:
                    type: string
                  price:
                    type: object
                    properties:
                      currency:
                        type: string
                      total:
                        type: string
                      base:
                        type: string
                  amenities:
                    type: array
                    items:
                      type: string
                  checkInDate:
                    type: string
                  checkOutDate:
                    type: string
                  guests:
                    type: object
                    properties:
                      adults:
                        type: number
                      children:
                        type: number
                      infants:
                        type: number
                  boardType:
                    type: string
                  paymentPolicy:
                    type: string
                  bestRate:
                    type: boolean
                  includeClosed:
                    type: boolean
                  lang:
                    type: string

paths:
  /api/amadeus/airports:
    get:
      tags:
        - Amadeus
      summary: Retrieve airports
      description: Retrieve airports
      parameters:
        - in: query
          name: keyword
          required: true
          schema:
            type: string
          description: Keyword to search for airports
      responses:
        "200":
          description: List of airports
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      airports:
                        type: array
                        items:
                          type: object
                          properties:
                            iataCode:
                              type: string
                            name:
                              type: string
                            cityCode:
                              type: string
                            city:
                              type: string
                            countryName:
                              type: string
                            region:
                              type: string
                            timeZone:
                              type: string
                            latitude:
                              type: number
                            longitude:
                              type: number
  /api/amadeus/flightOffers:
    get:
      tags:
        - Amadeus
      summary: Search for flight offers
      description: Search for flight offers
      parameters:
        - in: query
          name: originLocationCode
          required: true
          schema:
            type: string
          description: Origin location code
        - in: query
          name: destinationLocationCode
          required: true
          schema:
            type: string
          description: Destination location code
        - in: query
          name: departureDate
          required: true
          schema:
            type: string
          description: Departure date
        - in: query
          name: returnDate
          required: false
          schema:
            type: string
          description: Return date
        - in: query
          name: adults
          required: true
          schema:
            type: number
          description: Number of adults
        - in: query
          name: children
          required: false
          schema:
            type: number
          description: Number of children
        - in: query
          name: infants
          required: false
          schema:
            type: number
          description: Number of infants
        - in: query
          name: travelClass
          required: false
          schema:
            type: string
            enum: [ECONOMY, PREMIUM_ECONOMY, BUSINESS, FIRST]
          description: Travel class
        - in: query
          name: includedAirlineCodes
          required: false
          schema:
            type: string
          description: Included airline codes
        - in: query
          name: excludedAirlineCodes
          required: false
          schema:
            type: string
          description: Excluded airline codes
        - in: query
          name: nonStop
          required: false
          schema:
            type: boolean
          description: Non-stop flights only
        - in: query
          name: currencyCode
          required: false
          schema:
            type: string
          description: Currency code
        - in: query
          name: maxPrice
          required: false
          schema:
            type: number
          description: Maximum price
        - in: query
          name: max
          required: false
          schema:
            type: number
          description: Maximum number of results
      responses:
        "200":
          description: Flight offers search result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlightOffersOutput"
  /api/amadeus/flightPrice:
    post:
      tags:
        - Amadeus
      summary: Get accurate real time price for flight
      description: Get accurate real time price for flight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlightOffersOutput"
      responses:
        "200":
          description: Flight price
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlightOffersOutput"
  /api/amadeus/bookFlight:
    post:
      tags:
        - Amadeus
      summary: Book a flight
      description: Book a flight
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlightOffersOutput"
      responses:
        "200":
          description: Flight booking
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlightOffersOutput"
  /api/amadeus/hotelsList:
    get:
      tags:
        - Amadeus
      summary: Search for hotels by city
      description: Search for hotels by city
      parameters:
        - name: cityCode
          in: query
          required: true
          schema:
            type: string
          description: The IATA code of the city
        - name: radius
          in: query
          required: false
          schema:
            type: number
          description: The radius around the city in which to search for hotels
        - name: radiusUnit
          in: query
          required: false
          schema:
            type: string
            enum: [MILE, KM]
          description: The unit of the radius (MILE or KM)
        - name: chainCodes
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
          description: Array of hotel chain codes. Each code is a string consisted of 2 capital alphabetic characters.
        - name: amenities
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
            enum: [SWIMMING_POOL, SPA, FITNESS_CENTER, AIR_CONDITIONING, RESTAURANT, PARKING, PETS_ALLOWED, AIRPORT_SHUTTLE, BUSINESS_CENTER, DISABLED_FACILITIES, WIFI, MEETING_ROOMS, NO_KID_ALLOWED, TENNIS, GOLF, KITCHEN, ANIMAL_WATCHING, BABY_SITTING, BEACH, CASINO, JACUZZI, SAUNA, SOLARIUM, MASSAGE, VALET_PARKING, BAR, LOUNGE, KIDS_WELCOME, NO_PORN_FILMS, MINIBAR, TELEVISION, WI-FI_IN_ROOM, ROOM_SERVICE, GUARDED_PARKG, SERV_SPEC_MENU]
          description: "List of amenities.\nAvailable values : SWIMMING_POOL, SPA, FITNESS_CENTER, AIR_CONDITIONING, RESTAURANT, PARKING, PETS_ALLOWED, AIRPORT_SHUTTLE, BUSINESS_CENTER, DISABLED_FACILITIES, WIFI, MEETING_ROOMS, NO_KID_ALLOWED, TENNIS, GOLF, KITCHEN, ANIMAL_WATCHING, BABY-SITTING, BEACH, CASINO, JACUZZI, SAUNA, SOLARIUM, MASSAGE, VALET_PARKING, BAR or LOUNGE, KIDS_WELCOME, NO_PORN_FILMS, MINIBAR, TELEVISION, WI-FI_IN_ROOM, ROOM_SERVICE, GUARDED_PARKG, SERV_SPEC_MENU"
        - name: ratings
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
          description: The ratings of the hotels
        - name: hotelScore
          in: query
          required: false
          schema:
            type: string
            enum: [BEDBANK, DIRECTCHAIN, ALL]
          description: The score of the hotels
      responses:
        "200":
          description: Hotel offers search result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HotelOffersOutput"
  /api/amadeus/hotelOffers:
    get:
      tags:
        - Amadeus
      summary: Search for hotel offers
      description: Search for hotel offers
      parameters:
        - name: cityCode
          in: query
          required: true
          schema:
            type: string
          description: The IATA code of the city
        - name: chainCodes
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
          description: Array of hotel chain codes. Each code is a string consisted of 2 capital alphabetic characters.
        - name: amenities
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
            enum: [SWIMMING_POOL, SPA, FITNESS_CENTER, AIR_CONDITIONING, RESTAURANT, PARKING, PETS_ALLOWED, AIRPORT_SHUTTLE, BUSINESS_CENTER, DISABLED_FACILITIES, WIFI, MEETING_ROOMS, NO_KID_ALLOWED, TENNIS, GOLF, KITCHEN, ANIMAL_WATCHING, BABY_SITTING, BEACH, CASINO, JACUZZI, SAUNA, SOLARIUM, MASSAGE, VALET_PARKING, BAR, LOUNGE, KIDS_WELCOME, NO_PORN_FILMS, MINIBAR, TELEVISION, WI-FI_IN_ROOM, ROOM_SERVICE, GUARDED_PARKG, SERV_SPEC_MENU]
          description: "List of amenities.\nAvailable values : SWIMMING_POOL, SPA, FITNESS_CENTER, AIR_CONDITIONING, RESTAURANT, PARKING, PETS_ALLOWED, AIRPORT_SHUTTLE, BUSINESS_CENTER, DISABLED_FACILITIES, WIFI, MEETING_ROOMS, NO_KID_ALLOWED, TENNIS, GOLF, KITCHEN, ANIMAL_WATCHING, BABY-SITTING, BEACH, CASINO, JACUZZI, SAUNA, SOLARIUM, MASSAGE, VALET_PARKING, BAR or LOUNGE, KIDS_WELCOME, NO_PORN_FILMS, MINIBAR, TELEVISION, WI-FI_IN_ROOM, ROOM_SERVICE, GUARDED_PARKG, SERV_SPEC_MENU"
        - name: ratings
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
            enum: [1, 2, 3, 4, 5]
          description: The ratings of the hotels
        - name: adults
          in: query
          schema:
            type: number
          required: false
          description: Number of adults
        - name : checkInDate
          in: query
          schema:
            type: string
            format: date
          required: false
          description: Check-in date
        - name : checkOutDate
          in: query
          schema:
            type: string
            format: date
          required: false
          description: Check-out date
        - name: priceRange
          in: query
          schema:
            type: string
          required: false
          description: Price range
        - name: currencyCode
          in: query
          schema:
            type: string
          required: false
          description: Currency
        - name: paymentPolicy
          in: query
          schema:
            type: string
            enum: [GUARANTEE, DEPOSIT, NONE]
          required: false
          description: Payment policy
        - name: boardType
          in: query
          schema:
            type: string
            enum: [ROOM_ONLY, BREAKFAST, HALF_BOARD, FULL_BOARD, ALL_INCLUSIVE]
          required: false
          description: Board type
        - name: lang
          in: query
          schema:
            type: string
          required: false
          description: Language
      responses:
        "200":
          description: Hotel offers search result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HotelOffersOutput"
