openapi: "3.0.0"
info:
  title: Notification
  version: "1.0.0"
  description: Notification Retrieval and Counter APIs
tags:
  - name: Notification
    description: Notification Retrieval and Counter APIs
paths:
  /api/notification/getNotificationsById/{id}:
    get:
      tags:
        - Notification
      summary: Get Notifications by Id and flag as read
      parameters:
        - name: id
          in: path
          description: Notified Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: All Notifications
        "500":
          description: Internal Server Error
        "404":
          description: Not Found
  /api/notification/getNotificationNumber/{id}:
    get:
      tags:
        - Notification
      summary: Get Notification unread Number
      parameters:
        - name: id
          in: path
          description: Notified Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Notification Number is retrieved
        "500":
          description: Internal Server Error
        "404":
          description: Not Found
