openapi: "3.0.0"
info:
  title: User API
  version: 1.0.0
  description: User management and retrieval
tags:
  - name: Users
    description: User management and retrieval
paths:
  /api/users/test:
    get:
      tags:
        - Users
      summary: Retrieve a list of users
      description: Retrieve a list of users from the database
      responses:
        200:
          description: A list of users.
  /api/users/createUser:
    post:
      tags:
        - Users
      summary: Create a new user
      description: Create a new user in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IUserInputDTO"
      responses:
        200:
          description: User created.
        400:
          description: Bad request.
        500:
          description: Internal server error.
  /api/users/loginUser:
    get:
      tags:
        - Users
      summary: Login user
      description: Login user in the system
      parameters:
        - in: query
          name: username
          schema:
            type: string
        - in: query
          name: email
          schema:
            type: string
        - in: query
          name: password
          required: true
          schema:
            type: string
      responses:
        200:
          description: User logged in.
        400:
          description: Bad request.
        500:
          description: Internal server error.

  /api/users/updateGovernor/{email}:
    put:
      tags:
        - Users
      summary: Update Governor
      description: Update Governor
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newEmail:
                  type: string
                name:
                  type: string
                phone_number:
                  type: string
                password:
                  type: string
                nation:
                  type: string  
      responses:
        200:
          description: Governor updated.
        400:
          description: Bad request.
        500:
          description: Internal server error.        
  /api/users/forgetPassword/{email}:
    get:
      tags:
        - Users
      summary: Forget password
      description: Forget password
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
      responses:
        200:
          description: Password reset link sent to email.
        400:
          description: Bad request.
        500:
          description: Internal server error.           
components:
  schemas:
    IUserInputDTO:
      type: object
      properties:
        name:
          type: string
        username:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum:
            - Admin
            - User
            - Guest
        phone_number:
          type: string
        date_of_birth:
          type: string
          format: date
          